spring:
  datasource:
    url: jdbc:mysql://rm-wz94k0l69605b622nwo.mysql.rds.aliyuncs.com:3306/easy_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Chen1027
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8082
swagger:
  enable: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
